# Generated by Django 5.0.1 on 2024-02-29 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdata',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='salinity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='iotdata',
            name='username',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
